services:
  db:
    container_name: mysql
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=SkiStationDB
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  spring_app:
    container_name: ski
    image: http://172.17.0.1:8082/ski:v150
    restart: on-failure
    build: .
    ports:
      - 9091:9091
    depends_on:
      - db
  nexus:
    image: sonatype/nexus3
    expose:
      - 8081
      - 8082
      - 8083
    ports:
      - "8082:8082"
      - "8083:8083"
      - "8081:8081"
    volumes:
      - ./volume:/nexus-data
    restart: always
volumes:
  mysql:
    driver: local
