version: '3.9'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3306:3306"

  springbootapp:
    build: .  # Use the correct build context where your Dockerfile is located
    image: ski_station_project
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/SkiStationDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    depends_on:
      - mysqldb

    version: '3'
  services:
    sonarqube:
      image: sonarqube:latest
      container_name: sonarqube
      ports:
        - "9000:9000"
        - "9092:9092"
      networks:
        - sonarqube_network
      environment:
        - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonar

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - nexus_network
    volumes:
      - nexus_data:/nexus-data

networks:
  sonarqube_network:
  nexus_network:

volumes:
  nexus_data:
